name: two_client_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  dartz: ^0.10.1
  file_picker: ^10.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  go_router: ^16.1.0
  http: ^1.4.0
  iconsax: ^0.0.8
  internet_connection_checker: ^3.0.1
  lottie: ^3.3.1
  meta: ^1.16.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  syncfusion_flutter_pdfviewer: ^27.1.48
  syncfusion_flutter_pdf: ^27.1.48
  signature: ^5.4.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/png/logo.png"

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
    - family: Almarai
      fonts:
        - asset: assets/fonts/almarai/Almarai-Light.ttf
          weight: 200
        - asset: assets/fonts/almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/almarai/Almarai-Bold.ttf
        - asset: assets/fonts/almarai/Almarai-ExtraBold.ttf
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/auth/
    - assets/icons/home/
    - assets/animation/
